version: "3.8"

services:
  nestjs-app:
    build:
      context: ./nestjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/nest_db
      NODE_ENV: development
    volumes:
      - ./nestjs-app:/app
      - /app/node_module
    restart: always

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

volumes:
  mongo-data:
